create table designation (id integer generated by default as identity, name varchar(255), primary key (id))
create table holiday (id integer generated by default as identity, closest boolean, description varchar(255), observed_date date, official_date date, version integer, primary key (id))
create table holiday_type (holiday_id integer not null, type_id integer not null)
create table role (id integer not null, authority varchar(255), version integer, primary key (id))
create table type (id integer not null, description varchar(255), version integer, primary key (id))
create table unique_uh_number_v (uh_number bigint not null, primary key (uh_number))
alter table holiday_type add constraint FKdtuw7dh6jpcy77tm5enudg253 foreign key (type_id) references type
alter table holiday_type add constraint FKm7afp1taso29uoi6ourt2s1us foreign key (holiday_id) references holiday
